name: incrementally_loading_listview
description: An extension of the list view widget for incrementally loading data on scrolling
version: 0.1.1
author: Michael Bui <maikub84@gmail.com>
homepage: https://github.com/MaikuB/incrementally_loading_listview

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

